config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :list, uniqueness: { scope: :movie }
  validates :comment, length: { minimum: 6 }, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @bookmark.list = @list
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @movie = Movie.find(params['bookmark']['movie_id'])
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [ @list, @bookmark ] do |b| %>
  <%= b.association :movie %>
  <%= b.input :comment %>
  <%= b.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <script src="https://kit.fontawesome.com/d98a3df8be.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to lists_path, class: "navbar-brand" do %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/stvnpzn" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Movies", "#", class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner-index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1350&q=80)">
  <div class="container">
    <h1>La liste de mes listes 😍</h1>
    <%= link_to 'Add new list', new_list_path, :class => "btn btn-flat" %>
  </div>
</div>

<div class="container cards-container">
  <% @lists.each do |list| %>
    <div class="card-product" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path list.photo.key, height: 300, crop: :fill %>)">
      <div class="card-product-infos">
        <h2><%= link_to list.name, list_path(list.id) %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |l| %>
  <%= l.input :name %>
  <%= l.input :photo, as: :file %>
  <%= l.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1590452522688-e919e18c9e96?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80)">
  <div class="container-show">
    <h1><%= @list.name %></h1>
    <%= link_to 'Add a movie', new_list_bookmark_path(@list.id), :class => "btn btn-flat-show" %>
  </div>
</div>

<div class="container-bookmark">
  <% @list.bookmarks.each do |bookmark| %>
  <div class="card-bookmark">
    <img src="<%= bookmark.movie.poster_url %>" />
    <div class="card-bookmark-infos">
      <h2><%= bookmark.movie.title %></h2>
      <p><%= bookmark.comment %></p>
      <%= link_to list_bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" }, :class => "card-remove-link" do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  </div>
  <% end %>
</div>